export const SERVER_URL = import.meta.env.VITE_SERVER_HOST;

export const IMGS_BASIC_URL = import.meta.env.VITE_SERVER_IMG_URL;

export enum HTTP_STATUS_ENUM {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500
}

export enum LOGIN_STATE_ENUM {
  LOGIN,
  LOGOUT,
  READY
}
